version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    volumes:
      # Mount models and uploads for persistence
      - ./backend/models:/app/models
      - backend_uploads:/app/uploads
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5002/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://localhost:5002

volumes:
  backend_uploads:

networks:
  app-network:
    driver: bridge
