#!/bin/bash

echo "🔧 Railway Deployment Helper"
echo "=================================="
echo ""
echo "❌ If you got 'Nixpacks was unable to generate a build plan' error:"
echo "   This happens because Railway sees both backend/ and frontend/ folders"
echo "   and doesn't know which one to deploy."
echo ""
echo "✅ SOLUTION: Deploy each folder separately"
echo ""
echo "🎯 In Railway Dashboard:"
echo ""
echo "1️⃣  DEPLOY BACKEND:"
echo "   • Click 'New Service' → 'GitHub Repo'"
echo "   • Select 'ImmigrantSlangster' repository"
echo "   • ⚠️  IMPORTANT: Set Root Directory to '/backend'"
echo "   • Environment variables:"
echo "     - FLASK_ENV=production"
echo "     - PYTHONPATH=/app"
echo ""
echo "2️⃣  DEPLOY FRONTEND:"
echo "   • Click 'New Service' → 'GitHub Repo'"
echo "   • Select 'ImmigrantSlangster' repository again"
echo "   • ⚠️  IMPORTANT: Set Root Directory to '/frontend'"
echo "   • Build Command: npm install && npm run build"
echo "   • Environment variables:"
echo "     - REACT_APP_API_URL=https://[your-backend-url].railway.app"
echo ""
echo "3️⃣  CONNECT SERVICES:"
echo "   • Get backend URL from backend service (Settings → Networking)"
echo "   • Update frontend REACT_APP_API_URL with backend URL"
echo "   • Redeploy frontend"
echo ""
echo "🌐 Your app will be live at the frontend URL!"
echo ""
echo "Need help? Check RAILWAY_STATUS.md for detailed instructions."
